name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check SSH connection
        run: |
          echo $env:AWS_KEY_PEM
          echo $SSH_KEY
          echo test, and deploy your project.
        env:
          SSH_KEY: ${{secrets.AWS_KEY_PEM}}
    
