# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{secrets.AWS_KEY_PEM}}
      SSH_BACK_USER: ${{ secrets.SSH_BACK_USER }}
      SSH_FRONT_USER: ${{ secrets.SSH_FRONT_USER }}
      PROD_BACK_SERVER: ${{secrets.PROD_BACK_SERVER}}
      PROD_FRONT_SERVER: ${{secrets.PROD_FRONT_SERVER}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Step for Back deployment
      - name: Back deployment
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/KeyAlgoflex.pem
          chmod 600 ~/.ssh/KeyAlgoflex.pem
          cat >>~/.ssh/config <<END
          Host staging
            HostName $PROD_BACK_SERVER
            User $SSH_BACK_USER
            IdentityFile ~/.ssh/KeyAlgoflex.pem
            StrictHostKeyChecking no
          END

#       - name: Check SSH connection
#         run: |
#          mkdir ~/.ssh
#          echo $SSH_KEY > KeyAlgoflex.pem
#          chmod 600 KeyAlgoflex.pem
#          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#          ssh -v -i KeyAlgoflex.pem ubuntu@ec2-35-180-253-31.eu-west-3.compute.amazonaws.com "pwd"
#         ssh -v -i KeyAlgoflex.pem ubuntu@$PROD_BACK_SERVER "pwd"
#         ssh -v -o StrictHostKeyChecking=no -i KeyAlgoflex.pem ubuntu@$PROD_BACK_SERVER "pwd"
#         echo $SSH_KEY | sed 's/./& /g'
#         echo $PROD_BACK_SERVER | sed 's/./& /g'
    
